### ISSUE TITLE
WordPress in a subdirectory

### ISSUE THREAD

**Issue by johnjamesjacoby** [aliso/vvv-site-wizard#13]
Would be nice to have a switch and nginx config to support installing WordPress in a subdirectory ala WP Skeleton: https://github.com/markjaquith/WordPress-Skeleton

You can see an example of the subdirectory rules in HHVVVM: https://github.com/johnjamesjacoby/hhvvvm/blob/master/nginx-wp-subdirectory.conf-sample#L40

**Comment by timoburmeister** [comment]
something new on this issue? would be nice to have WP in subfolder..

**Comment by bradp** [comment]
I'd suggest checking out [VV](https://github.com/bradp/vv), we have perfect support for WP Skeleton structured installs.

**Comment by JJJ** [comment]
VV works good enough for this IMO.
