### ISSUE TITLE
Please tag a stable version

### ISSUE THREAD

**Issue by jacobwgillespie** [aliso/vvv-site-wizard#19]
Hi!  I would like to submit a formula to install this via Homebrew, however they require that the formula be installing a tagged release, not simply HEAD (see https://github.com/Homebrew/homebrew/wiki/Acceptable-Formulae#stable-versions).  Can you tag a 1.0 release?  Thanks!

**Comment by iblamefish** [comment]
+1 :+1:

**Comment by bradp** [comment]
I'd suggest checking out [VV](https://github.com/bradp/vv), you can install with brew right now.
