### ISSUE TITLE
update vvv.dev homepage to list all created sites

### ISSUE THREAD

**Issue by rtpHarry** [aliso/vvv-site-wizard#41]
I have about 15 dev sites active in my VVV install now.

It would be nice if the vvv-site-wizard script could update vvv.dev so that it lists the sites it has created in there.

I guess part of the functionality is already built as you can run vvv and ask it to list the existing sites that way but an easily clickable html link would be better for quick development.

**Comment by topdown** [comment]
Not trying to hijack anything as I love this project but as an alternative quick list I have built a VVV Dashboard
https://github.com/topdown/VVV-Dashboard

**Comment by rtpHarry** [comment]
Thanks @topdown this looks perfect.

I guess trying to pull the focus of a site-wizard project off into a dashboard isn't the best solution. From the screenshots your project looks way better than I was imagining for the solution. 

Will try it out now :)

**Comment by rtpHarry** [comment]
This solved my issues. 

The only thing I would suggest is to add a link to this script as a recommended companion to vvv-site-wizard.
